apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myargocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nikgit7/test99.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
